export enum AccountsTypes {
    FETCH_SAVINGS_ACOUNT_DETAILS = '@@accounts/FETCH_SAVINGS_ACOUNT_DETAILS',
    SET_SAVINGS_ACCOUNT_LIST_DETAILS = '@@accounts/SET_SAVINGS_ACCOUNT_LIST_DETAILS',
    SET_SAVINGS_ACCOUNT_LIST_DETAILS_STATUS = '@@accounts/SET_SAVINGS_ACCOUNT_LIST_DETAILS_STATUS'
}